version: 2

sources:
  - name: airbnb
    schema: raw
    tables:
      - name: listings
        identifier: raw_listings
        
      - name: hosts
        identifier: raw_hosts
        
      - name: reviews
        identifier: raw_reviews
        loaded_at_field: date
        freshness:
          warn_after: {count: 7, period: day}   # Warning setelah 7 hari
          error_after: {count: 30, period: day} # Error setelah 30 hari